#!/bin/bash

if [ "$1" == "--assemble" ]; then
	#nasm -felf kernel.asm -o kernel.o
	i586-elf-as start.s -o start.o
	i586-elf-as kernel.s -o kernel.o
elif [ "$1" == "--compile" ]; then
	#i586-elf-gcc -S -masm=intel -c test.c -std=gnu99 -ffreestanding -O2 -Wall -Wextra
	i586-elf-g++ -S -masm=intel -c kernel.cpp -ffreestanding -O2 -Wall -Wextra -fno-exceptions -fno-rtti
elif [ "$1" == "--display" ]; then
	qemu-system-i386 -cdrom kernel.iso
elif [ "$1" == "--gcc" ]; then
	i586-elf-gcc -T linker.ld -o kernel.bin -ffreestanding -O2 -nostdlib kernel.o -lgcc
else
	#nasm -felf kernel.asm -o kernel.o
	i586-elf-as start.s -o start.o
	i586-elf-as kernel.s -o kernel.o
	i586-elf-gcc -T linker.ld -o kernel.bin -ffreestanding -O2 -nostdlib start.o kernel.o -lgcc
	cp kernel.bin iso/boot/kernel.bin
	grub-mkrescue -o kernel.iso iso
	qemu-system-i386 -cdrom kernel.iso
fi

